services:
  app:
    build: .
    container_name: duniversity_app
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=college_user
      - DB_PASSWORD=deereddy@123
      - GRIEVANCE_DB=grievance_db
      - LEAVE_DB=leave_db
      - TIMETABLE_DB=timetable_db
      - EXAMS_DB=exams_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    command: node server.js

  db:
    image: mysql:8.0
    container_name: duniversity_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  db_data: